### ISSUE TITLE
in Clisp cl-tk don't work with ffi backend

### ISSUE THREAD

**Issue by YievCkim** [marijnh/cl-tk#3]
Hello,

In Clisp, we get an error when trying to use FFI backend:

```
CL-TK[7]> (toplevel-tk)

*** - FIND-CLASS: FFI-TK does not name a class
The following restarts are available:
ABORT          :R1      Abort main loop
Break 1 CL-TK[8]> 

```

libtcl and libtk are present, and CFFI is present and working properly:

```
CFFI[12]> (CFFI:LOAD-FOREIGN-LIBRARY "libtcl.so")
#<FOREIGN-LIBRARY LIBTCL.SO-6867 "libtcl.so">
CFFI[13]> (CFFI:LOAD-FOREIGN-LIBRARY "libtk.so")
#<FOREIGN-LIBRARY LIBTK.SO-6876 "libtk.so">
```

Thanks

**Comment by marijnh** [comment]
I'm no longer supporting this project -- if you figure out the problem and submit a sensible patch, I'll merge it. But I'm not going to debug the problem.

**Comment by YievCkim** [comment]
Ok no problem. I'll try to debug it. Thanks for your reply.
